### ISSUE TITLE
一些关于2.3.52的使用疑惑

### ISSUE THREAD

**Issue by TH2403y** [LoveFurina/YunliSR#1]
你好，虽然知道这个是存储用仓库，还是想询问一下我遇到的一些问题。
我依照教程将cn2.3.52的各项url填进dispatch并构建出新的程序，可游戏客户端一进去就提示“已经有新版本 请到客户端进行更新”
这里有进行mhypbase.dll的替换 他的弹窗出现了 但是没有输出内容
我不清楚原因，望大佬教教
![image](https://github.com/LoveFurina/YunliSR/assets/86739442/e761148a-5630-4951-b0ae-ce8b49b57319)

**Comment by TH2403y** [comment]
眼瞎了

**Comment by LoveFurina** [comment]
解决了就好
